import { Inter } from "next/font/google";
import "./globals.css";
import SiteNavbar from "@/components/SiteNavbar";
import SiteFooter from "@/components/SiteFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CyberDev Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SiteNavbar />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
